// New continuation draft: initial encounter remains in story.js, unchanged.
const XIAOCHU_SCRIPTS = {
  xiaochu_home: [
    { speaker: 'narrator', text: '無名推開家門，往旁邊讓了一步。小初卻停在門外。' },
    { speaker: 'wuming', text: '怎麼了？' },
    { speaker: 'xiaochu', text: '我也可以進去？' },
    { speaker: 'wuming', text: '不然要隔著門說話嗎？' },
    { speaker: 'xiaochu', text: '……打擾了！' },
    { speaker: 'narrator', text: '她跨過門檻，四下張望。無名把桌旁堆著的雜物挪開，拉出一張椅子。' },
    { speaker: 'xiaochu', text: '你不用特地收。我又不會嫌亂。' },
    { speaker: 'wuming', text: '這是給妳的位子。' },
    { speaker: 'narrator', text: '小初低頭看著椅子，過了一會兒才坐下。' },
    { speaker: 'xiaochu', text: '你平常也會帶人回來嗎？' },
    { speaker: 'wuming', text: '會在旁邊教我打史萊姆的，妳是第一個。' },
    { speaker: 'xiaochu', text: '那件事還沒過去啊……' },
    { speaker: 'narrator', text: '無名笑了一下，把劍靠在桌邊。小初的視線跟著落了下去。' },
    { speaker: 'xiaochu', text: '我以前真的有練劍。不是隨便說說的。' },
    { speaker: 'wuming', text: '我相信啊。' },
    { speaker: 'xiaochu', text: '可是看到牠撲過來，我就只記得練習時要怎麼做。連喊錯了都不知道。' },
    { speaker: 'wuming', text: '下次不確定，就先告訴我妳看到了什麼。' },
    { speaker: 'xiaochu', text: '不用告訴你什麼時候揮劍？' },
    { speaker: 'wuming', text: '那個讓我自己來。妳幫我看後面。' },
    { speaker: 'xiaochu', text: '……好。這個我做得到。' },
    { speaker: 'narrator', text: '小初坐直了些。披風的一角掃過桌上攤開的手記。' },
    { speaker: 'xiaochu', text: '《旅人手記》？你也想去旅行？' },
    { speaker: 'wuming', text: '有機會的話。不過，我最近是在找另一件事。' },
    { speaker: 'narrator', text: '無名翻到記著誓言的那一頁，卻沒有急著把書推過去。' },
    { speaker: 'wuming', text: '有人告訴我，可以和留在人間的靈魂締結契約。' },
    { speaker: 'xiaochu', text: '……像我這樣的？' },
    { speaker: 'wuming', text: '嗯。妳願意的話，我可以把我知道的告訴妳。' },
    { speaker: 'xiaochu', text: '那要現在決定嗎？' },
    { speaker: 'wuming', text: '不用急。先聽完，再決定也可以。' },
    { speaker: 'narrator', text: '小初看了一眼書頁，把椅子往桌邊挪近了些。' },
    { speaker: 'xiaochu', text: '嗯。你說，我在聽。' },
  ],
  xiaochu_trust: [
    { speaker: 'narrator', text: '最後一隻怪物倒下。無名收住劍勢，回頭看向一直跟在身後的小初。' },
    { speaker: 'wuming', text: '剛才謝了。' },
    { speaker: 'xiaochu', text: '我只說了後面有動靜。' },
    { speaker: 'wuming', text: '對啊，所以我來得及轉身。' },
    { speaker: 'narrator', text: '小初抿住嘴角，還是沒能藏住笑。' },
    { speaker: 'xiaochu', text: '這次我有看清楚才喊。' },
    { speaker: 'wuming', text: '有聽出來。聲音比上次小。' },
    { speaker: 'xiaochu', text: '你到底是謝我，還是笑我啊？' },
    { speaker: 'wuming', text: '謝妳。真的。' },
    { speaker: 'narrator', text: '無名蹲下整理掉落的物品。小初走到路旁，望著樹林深處。' },
    { speaker: 'xiaochu', text: '以前有人經過，我也會跟著走一小段。' },
    { speaker: 'xiaochu', text: '有時候他們停下來，我以為是聽見我了。結果只是鞋子裡進了石頭。' },
    { speaker: 'narrator', text: '無名手上的動作慢了下來。' },
    { speaker: 'xiaochu', text: '後來我就不太敢喊了。一直沒有回答，還滿難受的。' },
    { speaker: 'wuming', text: '可是妳那天還是喊了。' },
    { speaker: 'xiaochu', text: '牠都要撞到你了啊。' },
    { speaker: 'narrator', text: '她說得很快，像是根本沒有想過別的選擇。' },
    { speaker: 'wuming', text: '……幸好妳有喊。' },
    { speaker: 'xiaochu', text: '嗯。幸好你有回頭。' },
    { speaker: 'narrator', text: '無名把東西收好，起身時，小初往他身旁靠近了半步。' },
    { speaker: 'xiaochu', text: '回去以後，可以再讓我看看那本書嗎？' },
    { speaker: 'wuming', text: '契約那一頁？' },
    { speaker: 'xiaochu', text: '嗯。我想把它聽完。' },
    { speaker: 'wuming', text: '好。回家慢慢說。' },
  ],
  xiaochu_choice: [
    { speaker: 'narrator', text: '小初在桌邊坐好，目光落在記著誓言的書頁上。' },
    { speaker: 'narrator', text: '無名把《旅人手記》攤在兩人之間，說起女神與靈魂契約的事。' },
    { speaker: 'xiaochu', text: '所以，契約以後，我會住進你的身體裡？' },
    { speaker: 'wuming', text: '嗯。等我真正走完自己的人生，妳就能跟我一起到女神那裡。不是現在就要走。' },
    { speaker: 'xiaochu', text: '那我還能跟你說話嗎？' },
    { speaker: 'wuming', text: '手記裡的人有互相說話。我想可以，但實際是什麼感覺，我也還不知道。' },
    { speaker: 'xiaochu', text: '你也第一次啊。' },
    { speaker: 'wuming', text: '對。所以不確定的地方，我不想亂答應妳。' },
    { speaker: 'narrator', text: '小初慢慢翻過一頁。她在靈魂使者被處死的記載前停了下來。' },
    { speaker: 'xiaochu', text: '……他們明明救了人。' },
    { speaker: 'wuming', text: '嗯。' },
    { speaker: 'xiaochu', text: '你看過這裡了，還願意？' },
    { speaker: 'narrator', text: '無名沒有立刻回答。他把捲起的書角輕輕壓平。' },
    { speaker: 'wuming', text: '我會怕。我也不知道以後會怎樣。' },
    { speaker: 'wuming', text: '不過，要不要和妳同行，我想自己決定。' },
    { speaker: 'xiaochu', text: '……那我也是。' },
    { speaker: 'narrator', text: '小初把手記轉回記著誓言的那一頁。' },
    { speaker: 'xiaochu', text: '我原本想，能找到一個聽得見我的人就好了。' },
    { speaker: 'xiaochu', text: '可是你真的帶我回來，還替我留了位子。我就想……以後也想跟你一起去。' },
    { speaker: 'wuming', text: '妳已經有幫上忙了。' },
    { speaker: 'xiaochu', text: '我知道。我不是在說自己沒用。' },
    { speaker: 'xiaochu', text: '我是想，以後也跟你一起去。不是遇到下一個聽得見我的人，就換一條路。' },
    { speaker: 'narrator', text: '她的聲音不大，這次卻沒有移開視線。' },
    { speaker: 'wuming', text: '如果妳還沒想好，不締約也可以留下來。那張椅子又不會收走。' },
    { speaker: 'xiaochu', text: '……我知道。' },
    { speaker: 'xiaochu', text: '所以我才想選你啊。' },
    { speaker: 'narrator', text: '無名愣了一下。小初先低下頭，指向書上的字。' },
    { speaker: 'xiaochu', text: '不過，這段真的要念出來？' },
    { speaker: 'wuming', text: '我之前也是這個反應。' },
    { speaker: 'xiaochu', text: '你先練一下好了。我不笑你。' },
    { speaker: 'wuming', text: '妳已經在笑了。' },
    { speaker: 'narrator', text: '兩人把手記留在桌上。窗邊的光安靜地照著那一頁，沒有催促誰。' },
  ],
  xiaochu_oath: [
    { speaker: 'narrator', text: '無名依著手記，在桌前站定。小初把披風理好，面向他。' },
    { speaker: 'wuming', text: '準備好了嗎？' },
    { speaker: 'xiaochu', text: '嗯。你呢？' },
    { speaker: 'wuming', text: '……有點緊張。' },
    { speaker: 'xiaochu', text: '我也是。那就慢慢念。' },
    { speaker: 'narrator', text: '無名看了一眼書頁，抬起頭。' },
    { speaker: 'wuming', text: '我在此立誓。從今以後，無論生老病死，我都將與你共同進退。' },
    { speaker: 'wuming', text: '只要你仍願意與我同行，我便不讓你獨自走完這段路。' },
    { speaker: 'narrator', text: '念完後，無名安靜地等著。小初握緊的手慢慢鬆開。' },
    { speaker: 'xiaochu', text: '我願意。' },
    { speaker: 'xiaochu', text: '我也會看著你沒注意到的地方。害怕的時候會告訴你，不懂的事……就一起學。' },
    { speaker: 'narrator', text: '微光從書頁旁浮起，沿著兩人的腳邊緩緩展開。女神留在這個家的祝福，回應了誓言。' },
    { speaker: 'xiaochu', text: '無名。' },
    { speaker: 'wuming', text: '嗯？' },
    { speaker: 'xiaochu', text: '以後也請多指教。' },
    { speaker: 'wuming', text: '我也是。' },
    { speaker: 'narrator', text: '小初向前伸出手。這一次，無名接住了她。光芒輕輕合攏，融進他的胸口。' },
  ],
  xiaochu_after: [
    { speaker: 'narrator', text: '光芒散去，桌前只剩無名一個人。他下意識望向空著的椅子。' },
    { speaker: 'wuming', text: '小初？' },
    { speaker: 'xiaochu', thought: true, text: '在這裡。' },
    { speaker: 'narrator', text: '聲音近得不像從房間裡傳來。無名眨了眨眼。' },
    { speaker: 'wuming', text: '聽得好清楚。' },
    { speaker: 'xiaochu', thought: true, text: '我也是。你不用喊那麼大聲。' },
    { speaker: 'wuming', text: '這句居然換妳說了。' },
    { speaker: 'narrator', text: '他聽見小初笑了。胸口原本繃緊的感覺，也跟著慢慢鬆開。' },
    { speaker: 'xiaochu', thought: true, text: '下次出門，要不要試試看讓我拿劍？' },
    { speaker: 'wuming', text: '可以。不過先找個安全的地方練習。' },
    { speaker: 'xiaochu', thought: true, text: '知道啦。這次不會逞強。' },
    { speaker: 'narrator', text: '無名合上手記，卻沒有把桌旁的椅子推回去。' },
  ],
};

// Retained for future relationship writing, not an active pre-contract gate.
const { xiaochu_trust, ...activeDialogues } = XIAOCHU_SCRIPTS;
export const XIAOCHU_DIALOGUES = activeDialogues;
export const XIAOCHU_DEFERRED_DIALOGUES = { xiaochu_trust };
