import assert from 'node:assert/strict';
global.window = { location: { search: '' } };
global.document = { getElementById: () => null, addEventListener: () => {}, dispatchEvent: () => {}, documentElement: {} };
global.setTimeout = () => {};
const { gameState, initGame, PHASES } = await import('../prototype/js/state.js');
const { makeBoss, makeMob, bossSummonTick, tickMonsters, tick, canUseCharacterAction } = await import('../prototype/js/combat.js');
const { clearGooArena, gooTick, popGoo } = await import('../prototype/js/goo.js');
const { BOSS_SUMMON_OPENING_MS, BOSS_SUMMON_CD_MS, GOO_SKILL_CD_MS, MASTER_TICK_MS } = await import('../prototype/js/constants.js');
initGame();
gameState.phase = PHASES.COMBAT;
gameState.activeOverlay = null;
const boss = makeBoss();
gameState.monsters = [boss];
assert.equal(boss.skillCd, 0);
assert.equal(boss.skill2Cd, 0);
for (let i = 0; i < BOSS_SUMMON_OPENING_MS / MASTER_TICK_MS - 1; i++) bossSummonTick(boss);
assert.equal(gameState.monsters.length, 1);
assert.equal(boss.skill2Cd, 0, 'opening wind-up is not cooldown');
bossSummonTick(boss);
assert.equal(gameState.monsters.length, 2);
assert.equal(boss.skill2Cd, BOSS_SUMMON_CD_MS);
clearGooArena();
gameState.gooOpeningCountdown = 800;
for (let i = 0; i < 7; i++) gooTick(boss);
assert.equal(gameState.gooSpawnCountdown, 0);
assert.equal(gameState.activeGooBatch, null);
gooTick(boss);
assert.ok(gameState.activeGooBatch);
assert.equal(gameState.gooSpawnCountdown, GOO_SKILL_CD_MS);
gameState.gooSpawnCountdown = 0;
gooTick(boss);
assert.equal(gameState.gooSpawnCountdown, 0, 'blocked batch must not silently restart cooldown');
const batch = gameState.activeGooBatch;
let removed = false;
const blob = { batch, el: { remove() { removed = true; } } };
gameState.activeGoos = [blob];
gameState.activeOverlay = 'dialogue';
popGoo(blob);
assert.equal(removed, false, 'dialogue pauses arena clicks as well as combat ticks');
const snapshot = [boss.skill2Cd, gameState.gooSpawnCountdown, gameState.gooOpeningCountdown];
tick();
assert.deepEqual([boss.skill2Cd, gameState.gooSpawnCountdown, gameState.gooOpeningCountdown], snapshot);
clearGooArena();
assert.equal(gameState.gooOpeningCountdown, 0);
assert.equal(gameState.gooSpawnCountdown, 0);
assert.equal(gameState.activeGooBatch, null);
gameState.activeOverlay = null;
const c = gameState.roster[0];
const hp = c.curHp;
const deadMob = makeMob();
deadMob.hp = 0;
deadMob.actionCountdown = 0;
gameState.monsters = [deadMob];
tickMonsters();
assert.equal(c.curHp, hp, 'zero HP enemies cannot act while awaiting death sweep');
assert.equal(canUseCharacterAction(c.id), false, 'cannot spend an action on dead enemies');
boss.hp = 0;
boss.actionCountdown = 0;
boss.summonOpeningMs = 0;
boss.skill2Cd = 0;
gameState.monsters = [boss];
tickMonsters();
assert.equal(c.curHp, hp);
assert.equal(gameState.monsters.length, 1, 'dead boss cannot summon');
assert.equal(gameState.activeGooBatch, null, 'dead boss cannot create arena mechanics');
console.log('encounter-lifecycle.test.js: all assertions passed');
