import assert from 'node:assert/strict';
global.window = { location: { search: '' } };
global.document = { getElementById: () => null, addEventListener: () => {}, dispatchEvent: () => {}, documentElement: {} };
global.setTimeout = () => {};
const { gameState, initGame, PHASES, calcAtk, STATUS_DEFS } = await import('../prototype/js/state.js');
const { CHAR_DEFS } = await import('../prototype/js/constants.js');
const { performSkill, performMonsterSkill, tickMonsters, tickCharacters, useCharacterAction, endRun, guardEnemyDamage } = await import('../prototype/js/combat.js');
const { tryEvade, tickSurvivalState } = await import('../prototype/js/wuming-combat.js');
const { growthLineValue } = await import('../prototype/js/ui-character.js');
const originalRandom = Math.random;
try {
  initGame();
  gameState.phase = PHASES.COMBAT;
  gameState.activeOverlay = null;
  const c = gameState.roster.find(c => c.id === 'wuming');
  const [stab, evade, opening] = CHAR_DEFS.wuming.skills;
  const m = { id: 'target', name: '測試怪', hp: 10000, maxHp: 10000, alive: true, atk: 30,
    atkInterval: 1000, actionCountdown: 0, skillCd: 99999,
    skill: { name: '攻擊', target: 'randomParty', cd: 8, effects: [{ type: 'damage', mult: 1 }] } };
  gameState.monsters = [m];
  c.curHp = c.maxHp = 1000;
  Math.random = () => .5;
  performSkill(c, stab, 0, m);
  assert.equal(m.hp, 10000 - Math.round(calcAtk(c) * 2));
  performSkill(c, evade, 1, m);
  assert.equal(c.evasionUntil, 4000);
  assert.equal(c.evasionChance, .5);
  assert.equal(c.skillCds[1], 8000);
  assert.equal(tryEvade(c), false, '50% boundary is a hit');
  assert.equal(c.openingUntil, 0);
  Math.random = () => .1;
  tickMonsters();
  assert.equal(c.curHp, 1000, 'ordinary attacks can miss');
  assert.equal(c.openingUntil, 10000);
  c.openingUntil = 0;
  performMonsterSkill(m);
  assert.equal(c.curHp, 1000, 'ordinary monster skills can miss');
  assert.equal(c.openingUntil, 10000);
  Math.random = () => .9;
  performMonsterSkill(m);
  assert.ok(c.curHp < 1000, 'evasion is not invulnerability');
  Math.random = () => .5;
  c.actionCountdown = 0;
  c.skillCds = [0, 99999, 0];
  const before = m.hp;
  tickCharacters([c]);
  assert.equal(m.hp, before - Math.round(calcAtk(c) * 3.2));
  assert.equal(c.openingUntil, 0);
  assert.equal(c.skillCds[2], 10000, 'ready opening takes priority');
  const next = m.hp;
  performSkill(c, opening, 2, m);
  assert.equal(m.hp, next - Math.round(calcAtk(c) * 2), 'bonus is consumed once');
  c.curHp = 500;
  useCharacterAction('wuming');
  assert.equal(c.curHp, 650);
  assert.equal(c.resolveUntil, 4000);
  assert.equal(c.manualActionCd, 18000);
  assert.equal(guardEnemyDamage(c, 100), 70);
  assert.equal(guardEnemyDamage(c, 100), 70, 'resolve lasts across multiple hits');
  assert.equal(c.counterUntil, 0, 'resolve never grants Xiaochu counter');
  useCharacterAction('wuming');
  assert.equal(c.curHp, 650, 'cooldown prevents repeated healing');
  c.manualActionCd = 0;
  c.curHp = 990;
  useCharacterAction('wuming');
  assert.equal(c.curHp, 1000, 'healing is capped at maximum HP');
  c.manualActionCd = 0;
  c.alive = false;
  c.curHp = 0;
  useCharacterAction('wuming');
  assert.equal(c.curHp, 0, 'cannot revive');
  c.alive = true;
  c.curHp = 1000;
  assert.ok(guardEnemyDamage(c, 100000) > c.curHp, 'lethal boss damage remains lethal');
  c.lineLevels.skill1 = 100;
  performSkill(c, evade, 1, m);
  assert.equal(c.evasionChance, .75);
  assert.match(growthLineValue(c, 'skill1', 100), /75.0%/);
  assert.match(growthLineValue(c, 'action', 0), /15.0%.*30.0%/);
  assert.ok(STATUS_DEFS.find(s => s.id === 'evasion').isActive(c));
  tickSurvivalState(c, 10000);
  assert.equal(c.evasionUntil, 0);
  assert.equal(c.resolveReduction, 0);
  c.openingUntil = 10000;
  endRun();
  assert.equal(c.openingUntil, 0);
  assert.equal(c.evasionUntil, 0);
  assert.equal(c.resolveUntil, 0);
  console.log('wuming-skills.test.js: all assertions passed');
} finally { Math.random = originalRandom; }
