import assert from 'node:assert/strict';
global.window = { location: { search: '' } };
global.document = { getElementById: () => null, addEventListener: () => {}, dispatchEvent: () => {}, documentElement: {} };
global.setTimeout = () => {};
const { gameState, initGame, PHASES, calcAtk, calcDef, rollDamage, STATUS_DEFS } = await import('../prototype/js/state.js');
const { CHAR_DEFS, MASTER_TICK_MS } = await import('../prototype/js/constants.js');
const { performSkill, performMonsterSkill, tickMonsters, tickCharacters, useCharacterAction, endRun, guardEnemyDamage } = await import('../prototype/js/combat.js');
const { clearGuardState, grantGuard, tickGuardState } = await import('../prototype/js/guard.js');
const { drainCombatEvents } = await import('../prototype/js/combat-events.js');
const { growthLineValue } = await import('../prototype/js/ui-character.js');
const originalRandom = Math.random;
Math.random = () => .5;
try {
  initGame();
  gameState.phase = PHASES.COMBAT;
  gameState.activeOverlay = null;
  gameState.party = ['xiaochu'];
  const c = gameState.roster.find(c => c.id === 'xiaochu');
  const [slash, guard, counter] = CHAR_DEFS.xiaochu.skills;
  const m = { id: 'target', name: '測試怪', hp: 10000, maxHp: 10000, alive: true, atk: 23,
    atkInterval: 1000, actionCountdown: 0, skillCd: 99999,
    skill: { name: '測試攻擊', target: 'randomParty', cd: 8, effects: [{ type: 'damage', mult: 1 }] } };
  gameState.monsters = [m];
  c.curHp = c.maxHp = 1000;
  assert.deepEqual(CHAR_DEFS.xiaochu.skills.map(s => s.img), ['xiaochu_skill1', 'xiaochu_skill2', 'xiaochu_skill3']);
  assert.equal(CHAR_DEFS.xiaochu.action.img, 'xiaochu_action');

  performSkill(c, slash, 0, m);
  assert.equal(m.hp, 10000 - Math.round(calcAtk(c) * 2));
  assert.equal(c.skillCds[0], 4000);
  performSkill(c, guard, 1, m);
  assert.equal(c.guardUntil, 8000);
  assert.equal(c.skillCds[1], 8000);
  assert.ok(STATUS_DEFS.find(s => s.id === 'guard').isActive(c));
  const baseDamage = Math.round(m.atk - calcDef(c));
  tickMonsters();
  assert.equal(c.curHp, 1000 - Math.round(baseDamage * .4));
  assert.equal(c.guardUntil, 0);
  assert.equal(c.counterUntil, 10000);
  assert.ok(drainCombatEvents().some(e => e.type === 'shieldBlock'));
  const beforeSecond = c.curHp;
  m.actionCountdown = 0;
  tickMonsters();
  assert.equal(c.curHp, beforeSecond - baseDamage, 'guard only reduces one hit');

  const beforeCounter = m.hp;
  c.skillCds = [0, 0, 0];
  c.actionCountdown = 0;
  tickCharacters([c]);
  assert.equal(m.hp, beforeCounter - Math.round(calcAtk(c) * 3.5), 'ready counter wins over slash');
  assert.equal(c.counterUntil, 0);
  assert.equal(c.skillCds[2], 12000);
  const beforeNormal = m.hp;
  performSkill(c, counter, 2, m);
  assert.equal(m.hp, beforeNormal - Math.round(calcAtk(c) * 2));

  performSkill(c, guard, 1, m);
  c.dodgeUntil = 1000;
  performMonsterSkill(m);
  assert.equal(c.guardUntil, 8000, 'miss does not spend guard');
  c.dodgeUntil = 0;
  const beforeSkillHit = c.curHp;
  performMonsterSkill(m);
  assert.equal(c.curHp, beforeSkillHit - Math.round(baseDamage * .4));
  assert.equal(c.counterUntil, 10000);

  useCharacterAction(c.id);
  assert.equal(c.manualActionCd, 16000);
  assert.equal(c.guardUntil, 8000);
  assert.equal(c.slashBoostPct, .5);
  assert.equal(gameState.partyBuff.until, 0, 'action no longer grants global attack buff');
  const beforeEmpowered = m.hp;
  performSkill(c, counter, 2, m);
  assert.equal(m.hp, beforeEmpowered - rollDamage(calcAtk(c) * 3.5 * 1.5));
  assert.equal(c.slashBoostUntil, 0);
  assert.equal(c.counterUntil, 0);
  useCharacterAction(c.id);
  assert.equal(c.slashBoostUntil, 0, 'cooldown blocks another activation');

  c.manualActionCd = 0;
  useCharacterAction(c.id);
  c.skillCds = [99999, 99999, 99999];
  c.actionCountdown = 0;
  tickCharacters([c]);
  assert.ok(c.slashBoostUntil > 0, 'ordinary attacks do not consume slash boost');
  const beforeSlash = m.hp;
  performSkill(c, slash, 0, m);
  assert.equal(m.hp, beforeSlash - Math.round(calcAtk(c) * 2 * 1.5));
  assert.equal(c.slashBoostUntil, 0);

  c.lineLevels.skill1 = 100;
  c.lineLevels.action = 100;
  performSkill(c, guard, 1, m);
  assert.equal(c.guardReduction, .85, 'upgrades cap reduction below immunity');
  c.guardUntil = 2000;
  grantGuard(c, .6, 8);
  assert.equal(c.guardReduction, .85, 'weaker guard does not replace stronger guard');
  assert.equal(c.guardUntil, 8000);
  c.manualActionCd = 0;
  useCharacterAction(c.id);
  assert.equal(c.slashBoostPct, 1);
  assert.equal(c.manualActionCd, 8000);
  assert.match(growthLineValue(c, 'skill1', 100), /85%/);
  assert.match(growthLineValue(c, 'skill2', 100), /7.00/);
  assert.match(growthLineValue(c, 'action', 100), /100.0%/);
  assert.equal(guardEnemyDamage(c, 0), 0);
  assert.equal(c.guardUntil, 8000, 'zero damage does not spend guard');
  tickGuardState(c, 8000);
  assert.equal(c.guardUntil, 0);
  assert.equal(c.slashBoostUntil, 0);
  c.counterUntil = MASTER_TICK_MS;
  c.actionCountdown = 99999;
  tickCharacters([c]);
  assert.equal(c.counterUntil, 0, 'counter expires while waiting for an action');

  clearGuardState(c);
  grantGuard(c, .6, 8);
  c.curHp = 1000;
  m.skill.effects = [{ type: 'damage', mult: 1 }, { type: 'damage', mult: 1 }];
  performMonsterSkill(m);
  assert.equal(c.curHp, 1000 - Math.round(baseDamage * .4) - baseDamage, 'multi-hit skill consumes guard only on first hit');
  m.skill.effects = [{ type: 'damage', mult: 1 }];
  grantGuard(c, .6, 8);
  c.curHp = 1;
  performMonsterSkill(m);
  assert.equal(c.alive, false, 'guard does not prevent lethal remaining damage');
  assert.equal(c.curHp, 0);

  grantGuard(c, .6, 8);
  c.counterUntil = 10000;
  c.slashBoostUntil = 8000;
  endRun();
  assert.equal(c.guardUntil, 0);
  assert.equal(c.counterUntil, 0);
  assert.equal(c.slashBoostUntil, 0);
  clearGuardState(c);
  initGame();
  assert.equal(gameState.roster.find(c => c.id === 'xiaochu').guardUntil, 0);
} finally { Math.random = originalRandom; }
console.log('xiaochu-skills.test.js: all assertions passed');
